name: 🚀 Self-hosted Runner Test

on: 
  push:
    branches: [ "main", "master" ]
  workflow_dispatch: 

jobs:
  build:
    runs-on: self-hosted 
    
    steps:
      - name: 1. 접속된 서버의 호스트네임 확인
        run: hostname
        
      - name: 2. 실행 중인 사용자 계정 확인
        run: whoami
        
      - name: 3. 현재 작업 경로 확인
        run: pwd
